"""Add Credit Card fields

Revision ID: 134b0ec5f50b
Revises:
Create Date: 2026-02-09 11:42:25.223299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134b0ec5f50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_total', sa.Numeric(precision=15, scale=2), nullable=True, server_default='15000.00'))
        batch_op.add_column(sa.Column('limite_usado', sa.Numeric(precision=15, scale=2), nullable=True, server_default='0.00'))
        batch_op.add_column(sa.Column('fatura_fechada', sa.Boolean(), nullable=True, server_default='0'))
        # Using a fixed date for existing records is safer than nullable=False without default
        # But SQLite DATE is just a string, so '2025-01-01' works
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=False, server_default='2025-01-01'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes', schema=None) as batch_op:
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('fatura_fechada')
        batch_op.drop_column('limite_usado')
        batch_op.drop_column('limite_total')

    # ### end Alembic commands ###
