"""Add verification support

Revision ID: 8aafd63f34ed
Revises: 7793fa110906
Create Date: 2026-02-19 19:25:32.688360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aafd63f34ed'
down_revision = '7793fa110906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('senha_transacao', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contas',
    sa.Column('numero_conta', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_conta')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=16), nullable=False),
    sa.Column('validade', sa.String(length=5), nullable=False),
    sa.Column('cvv', sa.String(length=3), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('limite_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('limite_usado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fatura_fechada', sa.Boolean(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('chaves_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('investimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=True),
    sa.Column('taxa_anual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resgatado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['Clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Emprestimos',
    sa.Column('id_emprestimo', sa.Integer(), nullable=False),
    sa.Column('numero_conta', sa.Integer(), nullable=True),
    sa.Column('valor_emprestimo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('juros', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prazo', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['numero_conta'], ['Contas.numero_conta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_emprestimo')
    )
    op.create_table('Transacoes',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('numero_conta', sa.Integer(), nullable=True),
    sa.Column('tipo_transacao', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['numero_conta'], ['Contas.numero_conta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transacoes')
    op.drop_table('Emprestimos')
    op.drop_table('investimentos')
    op.drop_table('chaves_pix')
    op.drop_table('cartoes')
    op.drop_table('audit_logs')
    op.drop_table('Contas')
    op.drop_table('verification_codes')
    op.drop_table('Clientes')
    # ### end Alembic commands ###
